apiVersion: v1
kind: Service
metadata:
        name: ftps-service
        labels:
                app: ftps
spec:
        selector:
                app: ftps
        type: LoadBalancer
        ports:
                - port: 21
                  name: ftps-data
                  targetPort: 21
                  nodePort: 21
                - port: 30020
                  name: ftps-pasv-data
                  targetPort: 30020
                  nodePort: 30020

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: ftps-deployment
        labels:
                app: ftps
spec:
        selector:
                matchLabels:
                        app: ftps
        replicas: 1
        template:
                metadata:
                        name: ftps-pod
                        labels:
                                app: ftps
                spec:
                        containers:
                                - name: ftps-container
                                  image: ftps_img
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 21
                                            name: ftps-data
                                          - containerPort: 30020
                                            name: ftps-psv-data