apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf_img
          imagePullPolicy: Never
          volumeMounts:
            - name: docker-unix-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-unix-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket